### ISSUE TITLE
4. fejezet (az új módszer)

### ISSUE THREAD

**Issue by Gergo1912** [Gergo1912/Szakdolgozat#6]
Ebben a fejezetben volt a legtöbb javítani való.
https://github.com/Gergo1912/Szakdolgozat/commit/edd74f7dfa4aea0e8bf8f1c35da6d56eb9771f9c
Ebben a commitban van a javítás lényegi része.

https://github.com/Gergo1912/Szakdolgozat/commit/cd94ed1d0e3c7d05c3ad7aece3ada2c616aa1f31
Itt a pszeudó kódban maradt hibákat javítottam

https://github.com/Gergo1912/Szakdolgozat/commit/6176889ae8f3881e07d6ee0a6bb95d72b77e7177
Ebben pedig a tegnapi nap bennhagyott elírások javítása van

**Comment by hegyhati** [comment]
Rendben van.
