### ISSUE TITLE
Előadás diasor

### ISSUE THREAD

**Issue by Gergo1912** [Gergo1912/Szakdolgozat#7]
https://github.com/Gergo1912/Szakdolgozat/commit/3fe0667bb31389f930510b2761d4add3caf1e999

**Comment by hegyhati** [comment]
- [x] 1: kicsit hulyen torik meg a "tudomanyos fomunkatars", akar a temavezeto uten lehet sort torni, es akkor nincs ilyen.
- [ ] 3: ide mutatoba egy peldanak a blokkdiagrammjat, vagy valamit be lehetne tenni.
- [x] 7: eleg egy hivatkozas
- [x] 9: lehet elore copyznam ezt a thmax slide ele, hogy na, ilyen egy feladat, de ehhez kellene hallani mit mondasz el hozza. A 100 utan a kg itt is hulyen torik. 
- [x] Lehet inkabb a 8-asat hagynam ki / kesobbre. A hetediken elmondod, hogy van egy thmax algoritmus, utana mutatsz egy peldat, es hogy ez nem jo nekunk, mert az algoritmus feltetelezi a fix batch meretet, itt nincs meg, utana a mostani 10.  Ez szerintem igy kerek. 
- [x] Tetszik a 11-esen az abra. tok jo lenne, ha meglenne, hogy eddig mi volt, es ugy utana, hogy ehhez kepest mi van. Mondjuk az abra nem jo, mert a megvalosithatosagi metodus mar profitot maximalizal, es a jobb szelso meg a bound. vagy lehet rosszul gondoltam? 
- [ ] 12-15 tul sok szoveg, mely, valahogy egyszerusiteni kell. Akar egy par slide-os stepbysteppel. "Valtozast" hiaba reszletezed, a tobbseg az eredetit sem ismeri. Inkabb azt mutasd meg, mit csinal. 
- [x] 14 erre nem pazarolnek helyet, reszlet nagyon. 
- [x] 17 felesleges a piros meg a sarga, a gyorsitasok racsponton belul vannak, szoval azok nyilvan megegyeznek. eleg helyette egy oszlop. 

Franko amugy!

**Comment by Gergo1912** [comment]
Javítottam a leírt dolgokat: https://github.com/Gergo1912/Szakdolgozat/commit/9f5e9e96096c179ab91963a557de877b4a29f631

**Comment by hegyhati** [comment]
3: inkabb az abra aljara tennem, nem igy a tetejere. De lehet egy flow diagramm amugy jobban nezne ki. Nezd meg
10: egyelore jo lesz, hetfon meg kicsit csiszolunk rajta
